### ISSUE TITLE
About the pretrained model (Places2)

### ISSUE THREAD

**Issue by Zheng222** [Zhaoyi-Yan/Shift-Net#12]
Hello, @Zhaoyi-Yan, can you provide the pretrained model on Places2 training dataset? I would like to compare with your method. In your paper, you use `field` scene images from Places2, I want to know which `field` scene (`/f/field/cultivated` or `/f/field/wild`) is employed in your experiment?

**Comment by Zhaoyi-Yan** [comment]
Eeee，both I think.   You just train the model yourself.  The model seems to have been lost. I recommand you train the model in pytorch version, which should be faster.  `python train.py --batchSize=1 --use_spectral_norm_D=1 --which_model_netG='basic' --mask_type='center'`, run this line of code. Remember set batchSize=1 and train 30 epochs. Just take the model you train as the model I provide(I don't care...). Hope this can help you.

**Comment by Zheng222** [comment]
@Zhaoyi-Yan Thanks for your immediate reply. I want to know which `field` scene (`/f/field/cultivated` or `/f/field/wild`) is employed in your experiment?

**Comment by Zhaoyi-Yan** [comment]
Hi, I had a look at my notes written before. It seems that  the figures in the paper are obtained by training `/s/synagogue/outdoor`, `/b/butte` and `/c/canyon`.  Models trained on `/f/field/cultivated`, `/t/tundra`, `/v/valley` seems  a little worse for my case.

**Comment by Zheng222** [comment]
@Zhaoyi-Yan Thank you a lot!
